# Generated by Django 5.0.4 on 2024-04-08 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_time', models.FloatField()),
                ('sixty_foot_time', models.FloatField()),
                ('three_thirty_foot_time', models.FloatField()),
                ('eighth_mile_time', models.FloatField()),
                ('quarter_mile_time', models.FloatField()),
                ('trap_speed', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.car')),
            ],
        ),
    ]
